//private["_v","_i","_b","_p","_d","_ex","_a","_wd","_rd","_s","_id","_fire","_c","_sh"];
private _v=_this select 0;
private _i=_this select 1;
private _sh=_this select 2;
private _a=0;
private _s="";
private _rd=0;
private _p=getPos _i;
private _d=_v distance _i;
//private _str=format["%1\n\n%2",_i,(typeof _i)];copyToClipboard _str;hint _str;
if(isNull _i)exitWith{};
if(_d<30)exitWith{};
sleep .2;
if(isNull _i)exitWith{};
if((_v distance _i)>_d)exitWith{};
if!([_v,_i]call DAPS_fnc_AngleCheck)exitWith{};
private _id=getDir _i;
[_v,_id,_p,_i]call DAPS_fnc_React;
_rd=[_id,_v]call DAPS_fnc_RelDir2;
//if(_sh)exitWith{if((_rd<90)OR(_rd>270))exitWith{deleteVehicle _i;[_v,_rd,_p,_id]call DAPS_fnc_Afganit2}};
if(_sh)exitWith{
    if((_rd<90)OR(_rd>270))exitWith{
        if(_rd>180)then{_a=_v getVariable"dapsAmmoL"}else{_a=_v getVariable"dapsAmmoR"};
        if(_a>0)then{deleteVehicle _i};
        [_v,_rd,_p,_id]call DAPS_fnc_Afganit2;
    };
};
if((getNumber(configFile>>"CfgAmmo">>typeOf _i>>"hit"))>dapsHitLimit)exitWith{};
if((typeOf _i)in dapsExcludedAmmo)exitWith{};
private _fire=FALSE;
while{alive _i}do{
    _rd=[_id,_v]call DAPS_fnc_RelDir2;
    if((_rd<90)OR(_rd>270))exitWith{_fire=TRUE};
    sleep .001;
};
if!(_fire)exitWith{};
if(_rd>180)then{_a=_v getVariable"dapsAmmoL"}else{_a=_v getVariable"dapsAmmoR"};
if(_a<1)exitWith{};
private _ex=TRUE;
while{TRUE}do{
    if!(alive _i)exitWith{_ex=FALSE};
    if!(alive _v)exitWith{};
    _d=_v distance _i;
    if(_d>201)exitWith{_ex=FALSE};
    if(_d<40)exitWith{};
    sleep .0001;
};
if!(alive _v)exitWith{};
if!(_ex)exitWith{};
if!(alive _i)exitWith{};
_p=getPosATL _i;
if(((_p select 2)-((getPosATL _v)select 2))>5)exitWith{};
deleteVehicle _i;
_p remoteExec["DAPS_fnc_Blast"];
if(_rd>180)then{_s="LEFT"}else{_s="RIGHT"};
[_v,_s,_a]call DAPS_fnc_DeductAmmo;
[_v,_s,_rd,TRUE]remoteExec["DAPS_fnc_Report"];