#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "lxim_main",
            "A3_Characters_F_Exp",
            "A3_Characters_F",
            "cfp_uniforms",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_Ukraine",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_Russia",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "ace_thermals",
            "ace_refuel",
            "CUP_Core",
            "cba_xeh",
            "CFP_B_USARMY_WDL",
            "CUP_WheeledVehicles_HMMWV",
            "cfp_vehicles",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "ace_interaction",
            "ace_tagging",
            "ace_vehicles",
            "ace_cargo",
            "A3_Armor_F_Beta",
            "CFP_B_USARMY_2003_WDL",
            "CFP_B_USARMY_1991_WDL",
            "CUP_TrackedVehicles_M1_Abrams",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Soft_F_Enoch_UGV_02",
            "ace_cookoff",
            "ace_logistics_uavbattery",
            "ace_vehicle_damage",
            "CUP_TrackedVehicles_MTLB",
            "CUP_TrackedVehicles_FV510",
            "CUP_TrackedVehicles_Leopard1",
            "CUP_TrackedVehicles_Leopard2",
            "CUP_TrackedVehicles_MCV80",
            "CUP_TrackedVehicles_2S6M",
            "CUP_TrackedVehicles_AAV",
            "CUP_TrackedVehicles_BMP3",
            "CUP_TrackedVehicles_BMP",
            "CUP_TrackedVehicles_Bradley",
            "CUP_TrackedVehicles_ChallengerII",
            "CUP_TrackedVehicles_LCAC",
            "CUP_TrackedVehicles_M113",
            "CUP_TrackedVehicles_M1Abrams",
            "CUP_TrackedVehicles_M60",
            "CUP_TrackedVehicles_NewM113",
            "CUP_TrackedVehicles_T72",
            "CUP_TrackedVehicles_T90",
            "CUP_TrackedVehicles_T90M",
            "CUP_TrackedVehicles_ZSU23",
            "CUP_TrackedVehicles_Bulldog",
            "CUP_TrackedVehicles_M1A2Abrams",
            "CUP_TrackedVehicles_M270",
            "CUP_TrackedVehicles_T34",
            "CUP_TrackedVehicles_T55",
            "ace_compat_cup_vehicles",
            "CFP_B_USMC_DES",
            "CUP_Creatures_StaticWeapons",
            "CUP_Weapons_StaticWeapons",
            "ace_compat_cup_weapons_csw",
            "A3_Static_F",
            "A3_Static_F_AA_01",
            "A3_Static_F_AT_01",
            "CUP_WarfareBuildings",
            "ace_dragging",
            "ace_artillerytables",
            "CFP_B_USARMY_1991_DES",
            "CFP_B_USARMY_2003_DES",
            "CFP_B_USRANGERS_WDL",
            "CUP_AirVehicles_AH6",
            "ace_compat_cup_vehicles_fastroping",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F_Beta_Heli_Transport_01",
            "CUP_AirVehicles_412",
            "TFAR_IntercomDummy",
            "CFP_B_ILIDF",
            "CUP_AirVehicles_AH64",
            "cfp_b_gbarmy_wdl",
            "CUP_AirVehicles_F35",
            "A3_Air_F_Beta",
            "CFP_O_IRARMY",
            "CUP_AirVehicles_C130J",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "CUP_AirVehicles_A10",
            "CUP_AirVehicles_AN2",
            "CUP_AirVehciles_Cessna",
            "CUP_AirVehicles_DC3",
            "CUP_AirVehicles_L39",
            "CUP_AirVehicles_MV22",
            "CUP_AirVehicles_AmbientPlanes"
        };
        authorUrl = URL;
        author = "CPT Cury";
        authors[] = {"CPT Cury"};
        VERSION_CONFIG;
    };
};

#include "CfgEventHandlers.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"