[sqf.command_case]
severity = "Warning"
options.ignore = [
    "AGLtoASL",
    "ASLtoAGL",
    "WEST",
    "EAST",
    "INDEPENDENT",
    "RESISTANCE",
    "CIVILIAN",
    "getVehicleTiPars",
    "setVehicleTiPars"
]

[sqf.banned_commands]
options.banned = [
    "execVM",
]

[sqf.undefined]
enabled = true
options.check_orphan_code = true

[sqf.unused]
#enabled = true #many false positives without DEBUG_MODE_FULL
options.check_params = false

[sqf.shadowed]
enabled = false

[sqf.not_private]
enabled = true

[config.math_could_be_unquoted]
command_case = "Warning"
options.ignore = [
    "driverCanSee",
    "gunnerCanSee",
    "LockDetectionSystem"
    ]