#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            "I_PhilippinesArmy_Squad_Leader_Woodland_01",
            "I_PhilippinesArmy_Team_Leader_Woodland_01",
            "I_PhilippinesArmy_Rifleman_Woodland_01",
            "I_PhilippinesArmy_Autorifleman_Woodland_01",
            "I_PhilippinesArmy_Light_AT_Woodland_01",
            "I_PhilippinesArmy_Heavy_AT_Woodland_01",
            "I_PhilippinesArmy_Marksman_Woodland_01",
            "I_PhilippinesArmy_JTAC_Woodland_01",
            "I_PhilippinesArmy_Grenadier_Woodland_01",
            "I_PhilippinesArmy_Crewman_Woodland_01",
            "I_PhilippinesArmy_Pilot_Woodland_01",
            "I_PhilippinesArmy_Officer_Woodland_01",
            "I_PhilippinesArmy_M1A2_Abrams_Woodland_01",
            "I_PhilippinesArmy_M1126_ICV_M2_Woodland_01",
            "I_PhilippinesArmy_M2_HUMVEE_Woodland_01",
            "I_PhilippinesArmy_MK19_HUMVEE_Woodland_01",
            "I_PhilippinesArmy_UH_60_Woodland_01",
            "I_PhilippinesArmy_M2_STANDING_Woodland_01",
            "O_CebuArmy_Squad_Leader_woodland_01",
            "O_CebuArmy_Team_Leader_woodland_01",
            "O_CebuArmy_Rifleman_M4_woodland_01",
            "O_CebuArmy_Rifleman_M14_woodland_01",
            "O_CebuArmy_Autorifleman_woodland_01",
            "O_CebuArmy_Light_AT_woodland_01",
            "O_CebuArmy_Heavy_AT_woodland_01",
            "O_CebuArmy_Sniper_woodland_01",
            "O_CebuArmy_Grenadier_woodland_01",
            "O_CebuArmy_Crewman_woodland_01",
            "O_CebuArmy_Pilot_woodland_01",
            "O_CebuArmy_Officer_woodland_01",
            "O_CebuArmy_Tank_woodland_01",
            "O_CebuArmy_M1A1_Abrams_woodland_01",
            "O_CebuArmy_M2_Landrover_woodland_01",
            "O_CebuArmy_UH_1H_Transport_woodland_01",
            "O_CebuArmy_UH_1H_Gunship_woodland_01",
            "O_CebuArmy_UH_1H_Transport_Loaded_woodland_01",
            "O_CebuArmy_M2_Standing_woodland_01",
            "O_CebuArmy_M2_Lower_woodland_01",
            "O_CebuArmy_2B14_Mortar_woodland_01",
            "O_CebuArmy_SPG_woodland_01",
            "O_CebuArmy_TOW_Launcher_woodland_01",
            "O_CebuArmy_M163A1_Vad_woodland_01",
            "O_CebuArmy_AA_Missle_woodland_01"
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "A3_Air_F",
            "A3_Air_F_Beta_Heli_Transport_01",
            "A3_Air_F_Heli",
            "A3_Air_F_Heli_Light_01",
            "A3_Air_F_Heli_Light_02",
            "A3_Armor_F_Beta",
            "A3_Armor_F_Beta_APC_Tracked_01",
            "A3_Armor_F_Beta_APC_Tracked_02",
            "A3_Armor_F_Beta_APC_Wheeled_01",
            "A3_Armor_F_Beta_APC_Wheeled_02",
            "A3_Armor_F_EPB_APC_Tracked_03",
            "A3_Armor_F_EPB_MBT_03",
            "A3_Armor_F_Gamma_APC_Wheeled_03",
            "A3_Armor_F_Gamma_MBT_01",
            "A3_Armor_F_Gamma_MBT_02",
            "A3_Armor_F_Tank_AFV_Wheeled_01",
            "A3_Armor_F_Tank_LT_01",
            "A3_Armor_F_Tank_MBT_04",
            "A3_Characters_F",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Data_F_ParticleEffects",
            "A3_Soft_F",
            "A3_Soft_F_Enoch_UGV_02",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Static_F",
            "A3_Static_F_AA_01",
            "A3_Static_F_AT_01",
            "A3_Static_F_HMG_02",
            "ace_artillerytables",
            "ace_cargo",
            "ace_compat_cup_vehicles_fastroping",
            "ace_compat_cup_weapons_csw",
            "ace_cookoff",
            "ace_csw",
            "ace_dragging",
            "ace_gforces",
            "ace_interaction",
            "ace_logistics_uavbattery",
            "ace_medical_feedback",
            "ace_movement",
            "ace_refuel",
            "ace_tagging",
            "ace_thermals",
            "ace_vehicle_damage",
            "ace_vehicles",
            "cba_xeh",
            "CFP_B_AFARMY",
            "CFP_B_ILIDF",
            "CFP_B_KEARMY",
            "cfp_b_pesh",
            "CFP_B_USARMY_1991_DES",
            "CFP_B_USARMY_1991_WDL",
            "CFP_B_USARMY_2003_DES",
            "CFP_B_USARMY_2003_WDL",
            "CFP_B_USARMY_WDL",
            "CFP_B_USMC_DES",
            "CFP_B_USRANGERS_WDL",
            "CFP_I_IS",
            "CFP_I_WestUltra",
            "CFP_O_CHDKZ_SNW",
            "CFP_O_IS",
            "cfp_o_syarmy",
            "cfp_vehicles",
            "CUP_AirVehicles_412",
            "CUP_AirVehicles_AH6",
            "CUP_AirVehicles_UH1H",
            "CUP_AirVehicles_UH60",
            "CUP_Core",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_Ukraine",
            "CUP_Creatures_Military_USArmy",
            "CUP_Creatures_Military_USMC",
            "CUP_Creatures_StaticWeapons",
            "CUP_TrackedVehicles_2S6M",
            "CUP_TrackedVehicles_AAV",
            "CUP_TrackedVehicles_BMP",
            "CUP_TrackedVehicles_BMP3",
            "CUP_TrackedVehicles_Bradley",
            "CUP_TrackedVehicles_Bulldog",
            "CUP_TrackedVehicles_ChallengerII",
            "CUP_TrackedVehicles_FV510",
            "CUP_TrackedVehicles_LCAC",
            "CUP_TrackedVehicles_Leopard1",
            "CUP_TrackedVehicles_Leopard2",
            "CUP_TrackedVehicles_M113",
            "CUP_TrackedVehicles_M1_Abrams",
            "CUP_TrackedVehicles_M1A2Abrams",
            "CUP_TrackedVehicles_M1Abrams",
            "CUP_TrackedVehicles_M270",
            "CUP_TrackedVehicles_M60",
            "CUP_TrackedVehicles_MCV80",
            "CUP_TrackedVehicles_MTLB",
            "CUP_TrackedVehicles_NewM113",
            "CUP_TrackedVehicles_T34",
            "CUP_TrackedVehicles_T55",
            "CUP_TrackedVehicles_T72",
            "CUP_TrackedVehicles_T90",
            "CUP_TrackedVehicles_T90M",
            "CUP_TrackedVehicles_ZSU23",
            "CUP_WarfareBuildings",
            "CUP_Weapons_StaticWeapons",
            "CUP_WheeledVehicles_Boxer",
            "CUP_WheeledVehicles_BTR90",
            "CUP_WheeledVehicles_Hilux",
            "CUP_WheeledVehicles_HMMWV",
            "CUP_WheeledVehicles_LAV25",
            "CUP_WheeledVehicles_LR",
            "CUP_WheeledVehicles_Mastiff",
            "CUP_WheeledVehicles_Ridgeback",
            "CUP_WheeledVehicles_Stryker",
            "CUP_WheeledVehicles_Vodnik",
            "CUP_WheeledVehicles_Wolfhound",
            "tfar_core"
        };
        skipWhenMissingDependencies = 1;
        authorUrl = URL;
        author = "CPT Cury";
        authors[] = {"CPT Cury"};
        VERSION_CONFIG;
    };
};


#include "CfgEventHandlers.hpp"
#include "CfgFactionClasses.hpp"
#include "CfgGroups.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
