name: Arma

on:
  push:
    branches:
    - master
  pull_request:
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Check Strings
      run: python3 tools/check_strings.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'addons'

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives

  build:
    runs-on: windows-latest
    steps:
    - name: Install Arma 3 Tools
      uses: arma-actions/arma3-tools@master
      with:
        toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Checkout pull request
      uses: actions/checkout@v4
      if: ${{ github.event_name == 'pull_request_target' }}
      with:
        path: pullrequest
        ref: 'refs/pull/${{ github.event.number }}/merge'
    - name: Replace addons with pull request addons
      if: ${{ github.event_name == 'pull_request_target' }}
      run: |
        rm -r addons\
        rm -r optionals\
        rm -r include\
        xcopy /e /h /q pullrequest\addons addons\
        xcopy /e /h /q pullrequest\optionals optionals\
        xcopy /e /h /q pullrequest\include include\
    - name: Run HEMTT build
      run: hemtt build
    - name: Rename build folder
      run: mv .hemttout/build .hemttout/@ace
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
            name: lxim-latest
            path: release/lxim-latest.zip
